---
 
- name: apt-get install dependencies
  apt: name={{item}} state=latest update_cache=true
  with_items:
  - sudo
  - python-crypto
  - python-twisted
  - git
  - python-mysqldb

- name: Create Kippo user
  user: name=kippouser
        comment="Kippo User"
        shell=/bin/bash
        home=/home/kippouser

- name: Clone kippo repo
  sudo: yes
  sudo_user: kippouser
  git: repo=https://github.com/desaster/kippo.git
       dest=/home/kippouser/kippo

- name: Change sshd_config
  copy: src=sshd_config
        dest=/etc/ssh/sshd_config
  notify:
  - Restart SSH

- command: cp /home/kippouser/kippo/kippo.cfg.dist /home/kippouser/kippo/kippo.cfg

- name: Configure kippo.cfg
  ini_file: dest=/home/kippouser/kippo/kippo.cfg
            section={{ item.section}}
            option={{ item.option }}
            value={{ item.value }}
            owner=kippouser
            group=kippouser
  with_items:
    - { section: "honeypot", option: "hostname", value: "{{ kippo_hostname }}" }
    - { section: "database_mysql", option: "host", value: "{{ db_host }}" }
    - { section: "database_mysql", option: "database", value: "kippo-db" }
    - { section: "database_mysql", option: "username", value: "kippo" }
    - { section: "database_mysql", option: "password", value: "{{ db_password }}" }
    - { section: "database_mysql", option: "port", value: "3306" }

- name: Start Kippo
  sudo: yes
  sudo_user: kippouser
  command: /home/kippouser/kippo/start.sh

- name: Redirect port 2222 to 22
  command: iptables -t nat -A PREROUTING -p tcp --dport 22 -j REDIRECT --to-port 2222
